FROM alpine:3.5

RUN apk update && apk add python3 py3-curl \
&& pip3 install docker-py==1.10.6 tornado==4.5  pytz==2017.3 \
&& pip3 install --upgrade pip && rm -fr /root/.cache/pip \
&& ln -s /usr/bin/python3 /usr/bin/python \
&& mkdir -p /srv/tmpnb 

WORKDIR /srv/tmpnb/

COPY . /srv/tmpnb/

ENV DOCKER_HOST unix://docker.sock

CMD python orchestrate.py
