#!/usr/bin/env bash
export CONFIGPROXY_AUTH_TOKEN=`head -c 30 /dev/urandom | xxd -p`
export CONFIGPROXY_ENDPOINT="http://127.0.0.1:8001"
node_modules/.bin/configurable-http-proxy --default-target=http://127.0.0.1:9999 &
python dockworker.py $@ &
python orchestrate.py $@
kill %%
