#!/usr/bin/env bash

export DEBIAN_FRONTEND=noninteractive
sudo apt-get update && apt-get upgrade -y
sudo apt-get install nodejs-legacy build-essential curl python-pip python-dev supervisor npm
curl -sSL https://get.docker.io/ubuntu/ | sudo sh
